# Generated by Django 3.2.5 on 2021-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='irisdata',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Sepallength', models.FloatField()),
                ('Sepalwidth', models.FloatField()),
                ('Petallength', models.FloatField()),
                ('Petallwidth', models.FloatField()),
            ],
        ),
    ]
