# Generated by Django 3.2.5 on 2021-07-12 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='irisdata',
            old_name='Petallwidth',
            new_name='Petalwidth',
        ),
    ]
