# Generated by Django 3.2.5 on 2021-07-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iris', '0002_rename_petallwidth_irisdata_petalwidth'),
    ]

    operations = [
        migrations.AddField(
            model_name='irisdata',
            name='Irispred',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
